language: php

sudo: false

php:
  - '5.6'
  - '7.0'
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

matrix:
  allow_failures:
    - php: hhvm
